FROM debian:stable-20260112-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
              git \
              build-essential \
              cmake \
              python3 python3-dev \
         && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=

RUN git clone -b v1.6 https://github.com/mz-automation/libiec61850.git /tmp/libiec61850

RUN cd /tmp/libiec61850 && cmake . \
        && make \
        && make install

COPY . /tmp/iec61850_open_server

RUN cd /tmp/iec61850_open_server && cmake . \
       && make

WORKDIR /srv
RUN cd /tmp/iec61850_open_server && cp open_server /srv/libiec61850_server && cp -R plugin /srv/plugin

RUN mkdir -p /var/log/tpot && chmod 777 /var/log/tpot

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

CMD ["./libiec61850_server","eth0"]

